server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    name: DataSource
    url: jdbc:mysql://localhost:3306/cloud_order?serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mn_MySQL_123456
mybatis:
  type-aliases-package: top.co4.order.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS