server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    name: DataSource
    url: jdbc:mysql://localhost:3306/cloud_order?serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mn_MySQL_123456

mybatis:
  type-aliases-package: top.co4.user.pojo
  configuration:
    map-underscore-to-camel-case: true