server:
  port: 8081
spring:
  datasource:
    name: DataSource
    url: jdbc:mysql://localhost:3306/cloud_user?serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mn_MySQL_123456
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: 81.69.253.228:8848
      discovery:
        cluster-name: HN
        namespace: 73972537-f019-4e75-8a40-64e2150b5fd6


mybatis:
  type-aliases-package: top.co4.user.pojo
  configuration:
    map-underscore-to-camel-case: true