server:
  port: 8081
spring:
  datasource:
    name: DataSource
    url: jdbc:mysql://localhost:3306/cloud_user?serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mn_MySQL_123456
  application:
    name: user-service
ribbon:
  eager-load:
    enabled: true
    clients: user-service
mybatis:
  type-aliases-package: top.co4.user.pojo
  configuration:
    map-underscore-to-camel-case: true