server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    name: DataSource
    url: jdbc:mysql://localhost:3306/cloud_order?serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mn_MySQL_123456