server:
  port: 8081
spring:
  profiles:
    active: dev
  datasource:
    name: DataSource
    url: jdbc:mysql://localhost:3306/cloud_user?serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mn_MySQL_123456
feign:
  httpclient:
    max-connections: 200
    max-connections-per-route: 50
    enabled: true
mybatis:
  type-aliases-package: top.co4.user.pojo
  configuration:
    map-underscore-to-camel-case: true